//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingmakerResourceViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingmakerResourceViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy;+2 Lore Bonus for one Knowledge or Profession Skill;An institution of higher learning.;0;0;2;0;2;1;2;0;0;2;0;0;0;0;0;3;2;0;Library;University;&quot;Caster&apos;s Tower, Library, Magic Shop&quot;;N/A;1 Alchemy Lab/2 Bath/1 Bedroom/1 Bell Tower/1 Book Repository/1 Bunks/2 Classroom/1 Common Room/1 Courtyard/1 Greenhouse/1 Kitchen/1 Lavatory/1 Observation Dome/2 Office/1 Scriptorium/1 Sitting Room/1 Statue;Furnishing:Bedroom;2;52
        ///Alchemist;N/A;&quot;The laboratory and home of a crafter of poisons, potions or alchemical i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string buildingsCSV {
            get {
                return ResourceManager.GetString("buildingsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altar
        ///Armory
        ///Artisan&apos;s Workshop
        ///Artisan&apos;s Workshop
        ///Bath
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bell Tower
        ///Book Repository
        ///Cell
        ///Cell
        ///Cell
        ///Cell
        ///Cell
        ///Cell
        ///Cell
        ///Cell
        ///Ceremonial Room
        ///Courtyard
        ///Courtyard
        ///Crypt
        ///Defensive Wall
        ///Defensive Wall
        ///Escape Route
        ///Forge
        ///Gatehouse
        ///Gatehouse
        ///Gauntlet
        ///Gauntlet
        ///Hatchery
        ///Kitchen
        ///Lavatory
        ///Lodging
        ///Office
        ///Sanctum
        ///Storage
        ///Storage.
        /// </summary>
        internal static string FortRannick {
            get {
                return ResourceManager.GetString("FortRannick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnishing;Improves asthetic quality of room;This upgrade adds fancy furnishings to one room, such as wooden paneling, marble floors, fine ceramic teacups, lifelike paintings, and canopies for beds. The decoration is appropriate to the nature of the room and building. For example, if applied to a Bar frequented by soldiers, it includes patriotic heraldry and placards memorializing war heroes.;390;8;0;7;0;16
        ///Fortification;Increases room&apos;s durability;This upgrade can be applied to any room, reinforcing walls [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FurnishingsAndTrapsCSV {
            get {
                return ResourceManager.GetString("FurnishingsAndTrapsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;Wage;Skills;Description
        ///Abbot;4;&quot;Diplomacy,Heal,Knowledge&quot;;&quot;An Abbot is divine spellcaster trained to take care of a Temple or religious organization and its members. She&apos;s typically a 3rd-level adept, cleric, druid, or oracle, with light armor (or no armor, if an adept) and a weapon appropriate to her faith.&quot;
        ///Accountant;3;&quot;Appraise,Knowledge,Linguistics,Profession&quot;;&quot;An Accountant maintains financial records and balances an organization&apos;s or building&apos;s budget. He&apos;s typically a 3rd-level expert and no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManagersCSV {
            get {
                return ResourceManager.GetString("ManagersCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;Description;Teams
        ///Archivists;A skilled team of researchers to provide advice on a variety of subjects;&quot;2 Apprentice, 3 Sage, 1 Mage, 1 Priest&quot;
        ///Artisans&apos; Guild;Artisans and assistants who create quality goods.;&quot;1 Bureaucrat,2 Craftspeople,2 Laborers&quot;
        ///Bounty Hunters;Fighters trained to find and capture criminals and escapees.;&quot;1 Archers,1 Bureaucrats,1 Driver&quot;
        ///Brute Squad;A gang of well-armed professionals who throw their weight around on your behalf.;&quot;1 Robbers,2 Soldiers&quot;
        ///Cabal;A study group of pe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrganizationsCSV {
            get {
                return ResourceManager.GetString("OrganizationsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brodert Quink;DM;1200.3;12;3;8;0;Appraise:1,Climb:9,Diplomacy:2,Handle Animal:8,Heal:3,Knowledge:7,Perform:4,Profession:6,Stealth:5,Survival:5,Spellcraft:10
        ///Quink Brodert;DM;2100.7;21;7;2;1;Bluff:1,Craft:9,Disable Device:2,Intimidate:8,Linguistics:3,Sleight of Hand:7,Ride:4,Swim:6,Use Magic Device:5
        ///Lord of Parchment;James;2000;0;0;0;0;Bluff:10,Disable Device:13,Perception:6,Stealth:18,Spellcraft:10.
        /// </summary>
        internal static string OwnersCSV {
            get {
                return ResourceManager.GetString("OwnersCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstinent;&quot;The settlement religious or moral convictions force it to deny some of the world&apos;s more common vices. The settlement prohibits a common vice: usually alcohol is prohibited, but other abstinent settlements might ban stronger drugs, tobacco, prostitution, or even ‘indulgent&apos; foods like fine pastries, meat, or similar.&quot;;Advantage;2;0;1;0;0;-2;0;0;0;0;0;Lawful Only
        ///Abundant;&quot;The settlement has access to extraordinary natural resources: rich farmland, a deep lake, excellent hunting grounds nearby or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QualitiesCSV {
            get {
                return ResourceManager.GetString("QualitiesCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar
        ///Bath
        ///Bedroom
        ///Common Room
        ///Kitchen
        ///Lavatory
        ///Lodging
        ///Stall
        ///Storefront
        ///Game Room (illegal).
        /// </summary>
        internal static string RedRoseInn {
            get {
                return ResourceManager.GetString("RedRoseInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy Lab;10;10;0;0;10;0;Counts as an alchemist&apos;s laboratory (equipment);390;8;1;5;1;16;8;16;N/A;N/A;&quot;This room aids you when you&apos;re attempting Craft (Alchemy) checks, researching new alchemist&apos;s forumulae, and performing similar tasks. Up to three people can use the room at a time.&quot;;N/A
        ///Altar;0;0;3;0;0;0;Counts as a permanent fixture dedicate to your deity for the purpose of consecrate and similar spells.;210;2;1;2;1;4;2;8;N/A;N/A;&quot;This spiritual focal point has the iconography and materials required fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string roomCSV {
            get {
                return ResourceManager.GetString("roomCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altar
        ///Ballroom
        ///Bar
        ///Bath
        ///Bath
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bedroom
        ///Bunks
        ///Cell
        ///Common Room
        ///Courtyard
        ///Courtyard
        ///Crypt
        ///Defensive Wall
        ///Defensive Wall
        ///Defensive Wall
        ///Defensive Wall
        ///Defensive Wall
        ///Defensive Wall
        ///Escape Route
        ///Garden
        ///Gatehouse
        ///Kitchen
        ///Kitchen
        ///Labrynth
        ///Laundry
        ///Lavatory
        ///Lavatory
        ///Lodging
        ///Lodging
        ///Office
        ///Office
        ///Sanctum
        ///Secret Room
        ///Secret Room
        ///Secret Room
        ///Sitting Room
        ///Sitting Room
        ///Sitting Room
        ///Sports Field
        ///Stall
        ///Stall
        ///Stall
        ///Stall
        ///Statue
        ///Statue
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SamplePalace {
            get {
                return ResourceManager.GetString("SamplePalace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name=Coastal Cairns;Alignment=NN;Population=600;Qualities=Council,Abundant;NotableNPCs=&quot;Mayor Brodert Quink:Adept 3&quot;,&quot;Balor Hemlock:Fighter 4/Rogue 1&quot;;District:The Old Quarter=&quot;House,House,Castle,House,House&quot;;District:Prison District=&quot;Jail,Jail,Jail&quot;.
        /// </summary>
        internal static string settlementExample {
            get {
                return ResourceManager.GetString("settlementExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;GPEarnings;GoodsEarnings;InflucenceEarnings;LaborEarnings;MagicEarnings;CapitalEarnings;Benefit;GPCreate;GoodsCreate;InfluenceCreate;LaborCreate;MagicCreate;DaysCreate;MinSize;MaxSize;UpgradeFrom;UpgradeTo;Description;
        ///Acolyte;4;0;4;0;4;0;Spellcaster;440;2;2;2;3;3;1;1;N/A;&quot;Priest,Sage&quot;;&quot;An Acolyte is a newly trained divine spellcaster, sufficient for tending to the sick or advising on religious matters. An Acolyte is typically a 1st-level adept, cleric, druid, or oracle, with light armor (or no armor  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsCSV {
            get {
                return ResourceManager.GetString("TeamsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altar
        ///Bedroom
        ///Bell Tower
        ///Book Repository
        ///Cell
        ///Ceremonial Room
        ///Confessional
        ///Courtyard
        ///Crypt
        ///Garden
        ///Gatehouse
        ///Gauntlet
        ///Kitchen
        ///Lavatory
        ///Office
        ///Sitting Room
        ///Statue
        ///Storage.
        /// </summary>
        internal static string TempleOfIomede {
            get {
                return ResourceManager.GetString("TempleOfIomede", resourceCulture);
            }
        }
    }
}
